export type AbbrRule = {
  from: string;
  to: string;
  /** Only expand when the previous token looks like a proper name (Samet FK). */
  afterName?: boolean;
  /** Expand when one of these words appears nearby. */
  nearby?: string[];
  /** Skip if one of these words appears nearby. */
  unlessNearby?: string[];
};

/** Longest phrases first. Acronyms keep Turkish apostrophe suffixes. */
export const NEWS_ABBREVIATIONS: AbbrRule[] = [
  { from: "San. ve Tic. A.Ş.", to: "Sanayi ve Ticaret Anonim Şirketi" },
  { from: "San. ve Tic.", to: "Sanayi ve Ticaret" },
  { from: "Ltd. Şti.", to: "Limited Şirketi" },
  { from: "TFF 1. Lig", to: "Türkiye Futbol Federasyonu Birinci Lig" },
  { from: "Uzm. Dr.", to: "Uzman Doktor" },
  { from: "Op. Dr.", to: "Operatör Doktor" },
  { from: "Prof. Dr.", to: "Profesör Doktor" },
  { from: "Yrd. Doç.", to: "Yardımcı Doçent" },
  { from: "Öğr. Gör.", to: "Öğretim Görevlisi" },
  { from: "Arş. Gör.", to: "Araştırma Görevlisi" },
  { from: "Md. Yrd.", to: "Müdür Yardımcısı" },
  { from: "Bşk. Yrd.", to: "Başkan Yardımcısı" },
  { from: "Genel Müd.", to: "Genel Müdür" },
  { from: "Başkan V.", to: "Başkan Vekili" },
  { from: "Sayın Dr.", to: "Sayın Doktor" },
  { from: "AK Parti", to: "Adalet ve Kalkınma Partisi" },
  { from: "Saadet Partisi", to: "Saadet Partisi" },
  { from: "DEVA Partisi", to: "DEVA Partisi" },
  { from: "Vatan Partisi", to: "Vatan Partisi" },
  { from: "A Parti", to: "Anahtar Parti" },
  { from: "e-İmza", to: "elektronik imza" },
  { from: "e-imza", to: "elektronik imza" },
  { from: "Ar-Ge", to: "araştırma ve geliştirme" },
  { from: "AR-GE", to: "araştırma ve geliştirme" },
  { from: "Wi-Fi", to: "vay fay" },
  { from: "WiFi", to: "vay fay" },
  { from: "A.Ş.", to: "Anonim Şirket" },
  { from: "A.Ş", to: "Anonim Şirket" },
  { from: "Şti.", to: "Şirketi" },
  { from: "Ltd.", to: "Limited" },
  { from: "Koop.", to: "Kooperatifi" },
  { from: "San.", to: "Sanayi" },
  { from: "Tic.", to: "Ticaret" },
  { from: "T.C.", to: "Türkiye Cumhuriyeti" },
  { from: "Prof.", to: "Profesör" },
  { from: "Doç.", to: "Doçent" },
  { from: "Dr.", to: "Doktor" },
  { from: "Av.", to: "Avukat" },
  { from: "Uzm.", to: "Uzman" },
  { from: "Dt.", to: "Diş Hekimi" },
  { from: "Ecz.", to: "Eczacı" },
  { from: "Müh.", to: "Mühendis" },
  { from: "Em.", to: "Emekli" },
  { from: "Sn.", to: "Sayın" },
  { from: "Bşk.", to: "Başkan" },
  { from: "Müd.", to: "Müdür" },
  { from: "Mah.", to: "Mahallesi" },
  { from: "Mh.", to: "Mahallesi" },
  { from: "Cad.", to: "Caddesi" },
  { from: "Cd.", to: "Caddesi" },
  { from: "Sok.", to: "Sokak" },
  { from: "Sk.", to: "Sokak" },
  { from: "Blv.", to: "Bulvarı" },
  { from: "Bul.", to: "Bulvarı" },
  { from: "Apt.", to: "Apartmanı" },
  { from: "No.", to: ", numara" },
  { from: "vb.", to: "ve benzeri" },
  { from: "vs.", to: "vesaire" },
  { from: "bkz.", to: "bakınız" },
  { from: "SİHA'lar", to: "silahlı insansız hava araçları" },
  { from: "İHA'lar", to: "insansız hava araçları" },
  { from: "SİHA", to: "silahlı insansız hava aracı" },
  { from: "KOSGEB", to: "Küçük ve Orta Ölçekli İşletmeleri Geliştirme ve Destekleme İdaresi Başkanlığı" },
  { from: "TÜBİTAK", to: "Türkiye Bilimsel ve Teknolojik Araştırma Kurumu" },
  { from: "TÜİK", to: "Türkiye İstatistik Kurumu" },
  { from: "TBMM", to: "Türkiye Büyük Millet Meclisi" },
  { from: "RTÜK", to: "Radyo ve Televizyon Üst Kurulu" },
  { from: "ÖSYM", to: "Ölçme, Seçme ve Yerleştirme Merkezi" },
  { from: "İŞKUR", to: "Türkiye İş Kurumu" },
  { from: "AFAD", to: "Afet ve Acil Durum Yönetimi Başkanlığı" },
  { from: "BDDK", to: "Bankacılık Düzenleme ve Denetleme Kurumu" },
  { from: "TCDD", to: "Türkiye Cumhuriyeti Devlet Demiryolları" },
  { from: "TOKİ", to: "Toplu Konut İdaresi Başkanlığı" },
  { from: "MHK", to: "Merkez Hakem Kurulu", nearby: ["maç", "hakem", "futbol", "lig", "tff"] },
  { from: "VAR", to: "Video Yardımcı Hakem", nearby: ["maç", "hakem", "futbol", "lig", "gol"] },
  { from: "BAL", to: "Bölgesel Amatör Lig", nearby: ["lig", "futbol", "maç", "amatör"] },
  { from: "GFK", to: "Gaziantep Futbol Kulübü" },
  { from: "BJK", to: "Beşiktaş", nearby: ["maç", "futbol", "lig", "transfer", "gol", "teknik"] },
  { from: "ADS", to: "Adana Demirspor", nearby: ["maç", "futbol", "lig", "transfer"] },
  { from: "TFF", to: "Türkiye Futbol Federasyonu" },
  { from: "TSK", to: "Türk Silahlı Kuvvetleri" },
  { from: "MSB", to: "Millî Savunma Bakanlığı" },
  { from: "MEB", to: "Millî Eğitim Bakanlığı" },
  { from: "HSK", to: "Hâkimler ve Savcılar Kurulu" },
  { from: "YSK", to: "Yüksek Seçim Kurulu" },
  { from: "YÖK", to: "Yükseköğretim Kurulu" },
  { from: "SPK", to: "Sermaye Piyasası Kurulu" },
  { from: "SGK", to: "Sosyal Güvenlik Kurumu" },
  { from: "DSİ", to: "Devlet Su İşleri" },
  { from: "TRT", to: "Türkiye Radyo Televizyon Kurumu" },
  { from: "PTT", to: "Posta ve Telgraf Teşkilatı" },
  { from: "KGM", to: "Karayolları Genel Müdürlüğü" },
  { from: "AYM", to: "Anayasa Mahkemesi" },
  { from: "BAM", to: "Bölge Adliye Mahkemesi" },
  { from: "CMK", to: "Ceza Muhakemesi Kanunu" },
  { from: "TCK", to: "Türk Ceza Kanunu" },
  { from: "TMK", to: "Türk Medeni Kanunu" },
  { from: "İİK", to: "İcra ve İflas Kanunu" },
  { from: "HMK", to: "Hukuk Muhakemeleri Kanunu" },
  { from: "EGM", to: "Emniyet Genel Müdürlüğü" },
  { from: "MİT", to: "Millî İstihbarat Teşkilatı" },
  { from: "JÖH", to: "Jandarma Özel Harekât" },
  { from: "PÖH", to: "Polis Özel Harekât" },
  { from: "ÖKK", to: "Özel Kuvvetler Komutanlığı" },
  { from: "DHA", to: "Demirören Haber Ajansı" },
  { from: "STK", to: "sivil toplum kuruluşu" },
  { from: "NGO", to: "sivil toplum kuruluşu" },
  { from: "OSB", to: "Organize Sanayi Bölgesi" },
  { from: "KOBİ", to: "küçük ve orta büyüklükteki işletme" },
  { from: "KDV", to: "Katma Değer Vergisi" },
  { from: "ÖTV", to: "Özel Tüketim Vergisi" },
  { from: "TÜFE", to: "Tüketici Fiyat Endeksi" },
  { from: "ÜFE", to: "Üretici Fiyat Endeksi" },
  { from: "OGS", to: "Otomatik Geçiş Sistemi" },
  { from: "HGS", to: "Hızlı Geçiş Sistemi" },
  { from: "EDS", to: "Elektronik Denetleme Sistemi" },
  { from: "SMS", to: "kısa mesaj" },
  { from: "CHP", to: "Cumhuriyet Halk Partisi" },
  { from: "MHP", to: "Milliyetçi Hareket Partisi" },
  { from: "BBP", to: "Büyük Birlik Partisi" },
  { from: "DSP", to: "Demokratik Sol Parti" },
  { from: "AKP", to: "Adalet ve Kalkınma Partisi" },
  { from: "ABD", to: "Amerika Birleşik Devletleri" },
  { from: "USD", to: "Amerikan doları" },
  { from: "EUR", to: "avro" },
  { from: "GBP", to: "İngiliz sterlini" },
  { from: "U19", to: "on dokuz yaş altı" },
  { from: "U17", to: "on yedi yaş altı" },
  { from: "U15", to: "on beş yaş altı" },
  { from: "GP", to: "Gelecek Partisi", nearby: ["parti", "seçim", "milletvekili", "siyasi"] },
  { from: "DP", to: "Demokrat Parti", nearby: ["parti", "seçim", "milletvekili", "siyasi"] },
  { from: "GS", to: "Galatasaray", nearby: ["maç", "futbol", "lig", "transfer", "gol", "teknik"] },
  { from: "FB", to: "Fenerbahçe", nearby: ["maç", "futbol", "lig", "transfer", "gol", "teknik"] },
  { from: "TS", to: "Trabzonspor", nearby: ["maç", "futbol", "lig", "transfer", "gol"] },
  { from: "FK", to: "Futbol Kulübü", afterName: true, nearby: ["maç", "transfer", "futbol", "lig", "şampiyon", "gol", "teknik"] },
  { from: "SK", to: "Spor Kulübü", afterName: true, nearby: ["maç", "transfer", "futbol", "lig", "şampiyon", "spor"] },
  { from: "MV", to: "milletvekili" },
  { from: "AB", to: "Avrupa Birliği" },
  { from: "AA", to: "Anadolu Ajansı" },
  { from: "No:", to: ", numara" },
];
