ALTER TABLE `Election`
  ADD COLUMN `yskSecimId` INTEGER NULL,
  ADD COLUMN `yskSecimTuru` INTEGER NULL,
  ADD COLUMN `yskIlId` INTEGER NULL,
  ADD COLUMN `yskFocusIlce` VARCHAR(191) NULL,
  ADD COLUMN `yskSyncEnabled` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `yskLastSyncAt` DATETIME(3) NULL,
  ADD COLUMN `yskLastSyncError` TEXT NULL;
